import type { CSSProperties } from "react";

/** Co-located styles for ImportDrawer. */
export const s = {
  footer: { display: "flex", gap: 10, justifyContent: "flex-end" } satisfies CSSProperties,
  picker: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "14px 16px",
    borderRadius: 8,
    border: "1px dashed var(--border-strong)",
    background: "var(--bg-primary)",
    cursor: "pointer",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  filename: { marginTop: 10, fontSize: 13, color: "var(--text-secondary)", fontFamily: "var(--font-mono, monospace)" } satisfies CSSProperties,
  error: { marginTop: 10, fontSize: 13, color: "var(--err)" } satisfies CSSProperties,
  previewWrap: { marginTop: 18, display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  untrusted: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 7,
    background: "var(--bg-hover)",
    border: "1px solid var(--border)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  body: {
    margin: 0,
    padding: 14,
    borderRadius: 8,
    background: "var(--bg-primary)",
    border: "1px solid var(--border)",
    fontSize: 12.5,
    lineHeight: 1.5,
    fontFamily: "var(--font-mono, monospace)",
    whiteSpace: "pre-wrap",
    maxHeight: 320,
    overflow: "auto",
  } satisfies CSSProperties,
  ignoredHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  ignoredEmpty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  ignoredList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  ignoredItem: { display: "flex", alignItems: "center", gap: 8, fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  ignoredPath: { flex: 1, fontFamily: "var(--font-mono, monospace)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
} as const;
