import type React from "react";

export const s = {
  statRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    alignItems: "center",
    gap: 18,
    marginBottom: 16,
  },
  stat: {
    display: "inline-flex",
    alignItems: "baseline",
    gap: 6,
    fontSize: 13,
    color: "var(--text-muted)",
  },
  statNum: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  statusNote: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  reason: {
    fontSize: 12,
    color: "var(--text-muted)",
  },
  priorWrap: {
    marginTop: 14,
    borderTop: "1px solid var(--border)",
    paddingTop: 12,
  },
  priorHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 0",
    color: "var(--text-secondary)",
    textAlign: "left" as const,
  },
  priorLabel: {
    fontSize: 13,
    fontWeight: 600,
  },
  priorCount: {
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    borderRadius: 5,
    padding: "1px 7px",
  },
  priorList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
    marginTop: 8,
  },
  priorRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "6px",
    borderRadius: 6,
    textAlign: "left" as const,
    color: "var(--text-secondary)",
  },
  priorNum: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
  },
  priorTitle: {
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    flex: 1,
  },
  priorStatus: {
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "capitalize" as const,
    flexShrink: 0,
  },
} satisfies Record<string, React.CSSProperties>;
